services:
  michelclean:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: michelclean
    ports:
      - "3005:3005"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.services.michelclean.loadbalancer.server.port=3005"
    
      # HTTP (Port 80) → Redirect auf HTTPS
      - "traefik.http.routers.michelclean-http.entrypoints=frontendsecure"
      - "traefik.http.routers.michelclean-http.rule=Host(`www.michelclean.de`)"
      - "traefik.http.routers.michelclean-http.middlewares=michelclean-https"
      
      - "traefik.http.middlewares.michelclean-https.redirectscheme.scheme=https"
    
      # Redirect michelclean.de → www.michelclean.de
      - "traefik.http.routers.michelclean-root.entrypoints=frontendsecure"
      - "traefik.http.routers.michelclean-root.rule=Host(`michelclean.de`)"
      - "traefik.http.routers.michelclean-root.middlewares=michelclean-www-redirect"
      - "traefik.http.routers.michelclean-root.tls=true"
    
      - "traefik.http.middlewares.michelclean-www-redirect.redirectregex.regex=^https?://michelclean\\.de(.*)"
      - "traefik.http.middlewares.michelclean-www-redirect.redirectregex.replacement=https://www.michelclean.de$1"
      - "traefik.http.middlewares.michelclean-www-redirect.redirectregex.permanent=true"
    
      # HTTPS Router
      - "traefik.http.routers.michelclean.entrypoints=frontendsecure"
      - "traefik.http.routers.michelclean.rule=Host(`www.michelclean.de`)"
      - "traefik.http.routers.michelclean.tls=true"
      - "traefik.http.routers.michelclean.service=michelclean"
      - "traefik.http.routers.michelclean.tls.certresolver=leresolver"


networks:
  traefik-net:
    external: true
